databases:
  - name: traidr_pj
    databaseName: pennywise_db
    user: traidr
    plan: free

services:
  - type: web
    plan: free
    name: pennywise
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        value: postgres://traidr:41ROclsxv5cG8MKub7UGxcEHVJu4VAiG@dpg-cgf0249mbg50899ep5t0-a/pennywise_db
      - key: RAILS_MASTER_KEY
        sync: false
